### PR TITLE
Add installation of dependencies

### PR DESCRIPTION
**Pull request by wingZero21**
Add automatic installation of dependencies required for rpm build.

### CODE REVIEW

**Comment by juliogonzalez** [comment]
@wingZero21 thanks for your contribution.

Your change assumes that `s3fs-fuse-rpm` is being executed as root, which can't be assumed, so at least you should check if current user ID is 0 before calling yum.

However building RPMs as root is a bad and dangerous practice: https://serverfault.com/a/10051/245977

If you really need the dependencies installed with a script, I'd suggest another approach: a new script  `install-dependencies` that checks if user calling the script is root, then extracts build dependencies from the SPEC and install them.

**Comment by wingZero21** [comment]
Hi,

That is a valid point, however as you mentioned those dependancies are required in order to build the RPM so will need installing at some point. 

We generally have a user that will have access to install the packages (EG: A build user).

It could also be that the script is amended to use sudo so it ensures whoever the user is that it is running as has the appropriate permissions to install the package.

Cheers

**Comment by juliogonzalez** [comment]
@wingZero21 that would be assuming that sudo is installed, or that the user has the correct access to sudo.

I'd say: let's have it as a separate script called 'install-s3fs-fuse-build-dependencies' that needs to be called either as root or with su:

```bash
#!/bin/bash -e
if [ ${UID} -ne 0 ]; then
  echo "You need to run this script as root (or with sudo)"
  exit 1
fi
INSTALLDEPS=$(grep 'BuildRequires:' SPECS/s3fs-fuse.spec|tr '\n' ','|sed -e 's/BuildRequires:\w*//g'|sed -e 's/\s//g'|sed --e 's/,/ /g')
/usr/bin/yum install -y ${INSTALLDEPS}
```

Feel free to copy it to your branch and then commit & push.

Benefits of this separate script:

- We don't break current s3fs-fuse-rpm behaviour by requiring to run it as root, or with sudo
- We don't call yum each time (if packages are installed, it is not needed)
- We calculate dependencies automatically from the SPEC, if it ever changes, we don't need to touch the script, only the SPEC.

**Comment by juliogonzalez** [comment]
Superseded by https://github.com/juliogonzalez/s3fs-fuse-rpm/pull/24

**Pull request closed without merging**
